### PR TITLE
Add support for controls whose parent is not the uifigure.

### PR DESCRIPTION
**Pull request by davidn-IA**
This allows, for example, a text area inside a panel, to have the text
formatted with bold face font.  Previously this caused an error.

f = uifigure('Position', [680 558 560 420]);
p = uipanel(f,'Position',[20 20 520 380]);
txa = uitextarea(p, ...
'Value', 'Lorem ipsum', ...
'Position',[20 20 480 340]);
mlapptools.fontWeight(txa, 'bold');

### CODE REVIEW

**Comment by sco1** [comment]
Thanks for the catch, we haven't looked too much at UI elements that aren't direct children of the `UIFigure` object.

I would prefer to use [`ancestor`](https://www.mathworks.com/help/matlab/ref/ancestor.html) if you'd like to update & repoint the PR with something like the following instead:

    function [win] = getWebWindow(hUIObj)
        hUIFig = ancestor(hUIObj, 'figure');

If not, I can add & push sometime this afternoon.

**Comment by altmany** [comment]
Hi @davidn-IA, nice to see you here :-)

I think it would be better to leave the existing code as-is (i.e., a simple call to `mlapptools.getWebWindow`) and simply modify `getWebWindow()` to look not at the input arg directly but rather its figure ancestor (along the lines of what @sco1 just commented above)

**Comment by sco1** [comment]
Thanks @altmany, that makes more sense. I forgot that there are multiple calls to `getWebWindow` so it's smarter to fix there :)

I've updated my comment above.

**Comment by davidn-IA** [comment]
Did not realize ancestor worked with uifigure, thanks @sco1.  @altmany , it's about time I give something back. :-)

So maybe close this and re-post as an issue to fix getWebWindow? (also please see the other issue I posted, thanks!)

**Comment by Dev-iL** [comment]
@davidn-IA Feel free to add another commit to this PR to save time. When merging we'll just squash :)

**Comment by sco1** [comment]
Fix has been implemented & pushed with 88b82f6 (fat-fingered the commit message reference)

This can be closed, thanks again for spotting the issue!

**Pull request closed without merging**
