### PR TITLE
Latest modifications from Dev-iL (addressing #1, #6, #7)

### PR DESCRIPTION
**Pull request by Dev-iL**

### CODE REVIEW

**Comment by Dev-iL** [comment]
Looks like I forgot to update the Readme... :)

**Review by sco1 — DISMISSED** [review]
Other than `getWebElements` needing a warning toggle, LGTM. Addresses the current issues on both of my test machines.

**Comment by Dev-iL** [comment]
@sco1 Please merge when you're done testing (assuming there are no further comments).

**Comment by sco1** [comment]
Thanks @Dev-iL, you're a magician :)

**Pull request merged**
